<?php
require_once "header.php"; 

 echo '<div id="welcome">
 	<br>
    <span style="font-size:2.2em; font-family:later_on; font-weight:bold; letter-spacing:2.2px;">A Tale of Two Zodiacs</span>
    <br>';

    echo '<div style="width:600px; line-height: 1.3; letter-spacing: .05px;">
<p>Thousands of years ago, as astronomers mapped the stars in the sky, they noticed that certain stars appeared to be in a fixed position and other "stars" appeared to travel.  These travelling “stars”, of course, were the planets. They named the path that the planets were traveling in the Zodiac, and divided this path into 12 parts.  Each of these parts included a constellation for which it was named, and the signs in a Birth Chart were determined by which constellation your planets, sun and moon were “traveling” through at your time of birth.  Even though we now know that the planets are not traveling around the earth but the sun, this doesn’t change the philosophy that your signs are determined by the relationship of the planets sun and moon in the sky to the exact point you were born on earth.  This early Zodiac came to be called the Sidereal Zodiac, because sidereal means “in relation to the stars.”  To this day, Vedic Astrology uses the Sidereal Zodiac to calculate Birth Charts.</p>

<p>About 1800 years ago, when the Tropical Zodiac was created, the two Zodiacs generated almost exactly the same Birth Charts.  It’s possible that the introduction of the Tropical Zodiac went smoothly because there was little to no change when using this new Zodiac to calculate Birth Charts.  So 1800 years ago, if a neighbor who shared your birthday had her Birth Chart done by an astrologer using the Sidereal Zodiac and you had your Birth Chart done by an Astrologer using the Tropical Zodiac, there was likely no controversy when the two of you discussed yours signs together.</p>

<p>What eventually created the disparity in Birth Charts is the fact that every year the earth tilts slightly on its axis, creating a change in the relationship of the earth to the stars overhead.  This means that in relation to the earth, the stars overhead at this moment are in a slightly different place than they will be at exactly this moment one year from today.  The Sidereal Zodiac takes this change into account, so while someone born between March 21st and April 19th roughly 1800 years ago would have been born under the constellation of Aries.  Nowadays, someone would have to be born between April 14th and May 13th in order to be born under the constellation of Aries.</p>

<p>It was an astrologer named Claudius Ptolemy who created the Tropical Zodiac.  Ptolemy elected to divorce the Zodiac from the stars and tie it instead to the seasons and the solar year.  A solar year, also called a “tropical year,” is the time it takes for the sun to return to the same point in the sky, generally around one calendar year.  As such, Ptolemy’s Zodiac came to be known as the Tropical Zodiac.  Instead of considering the constellation the Sun was “passing through,” Ptolemy decided to divide the suns path into 12 parts and call these the different signs of the Zodiac. In his model, the Zodiac no longer corresponded with the constellations in the sky, so even if a person today were born under the constellation of Aries, Ptolemy’s Zodiac might call that person a Taurus.  This is the Zodiac used in Western Astrology.</p>

<p>Using the Tropical Zodiac makes it so that everyone born on the same day, no matter the year or the constellation over head, will have the same Birth Chart.  Because at Starma, we consider not just the relationship of the sun, the moon and the planets to the earth, but also the relationship of the stars, we choose to use the Sidereal Zodiac to calculate Birth Charts.  That being said, we believe astrology is an art, not a science.  Although for most of history astronomers were also astrologers, unlike astronomy, astrology cannot be proven in a scientific manner.  When you consider this, a belief that a Birth Chart should be determined by the Sun has as much merit as a belief that it should include the relationship of the stars.  Most of the features on Starma have been created using the Sidereal Zodiac, but for those of you interested in the Tropical Zodiac, we’ve included what we call the “Western View” on your profile.  Please enjoy the site, and email us with more questions.  We’ll be including a frequently asked questions section soon!</p>
</div>';

?>
<!---The Tropical Zodiac and the Sidereal Zodiac have been a topic of much discussion and debate amongst astrologers for about 1800 years.  But there once was a time when this debate did not exist because there was only one Zodiac, the Sidereal Zodiac.  In this article we will examine the history of the Zodiac, how one became two, and why we at Starma.com have chosen to stick with the Sidereal Zodiac. 
<Br><br>
Today, it is generally assumed that Hindu astrology (or Jyotish) uses the Sidereal Zodiac, and Western astrology uses the Tropical Zodiac.  However, many Western astrologers have been converting to the Sidereal Zodiac over the last 60 years or so.  In order to understand why we have chosen to use the Sidereal Zodiac, we have to back track a little and share with you the same path of information that led us to this decision.
<Br><br>
First, let's zoom way out from the details for a bit and begin with some very general history of astrology.  It is well documented that astrology has been used for thousands of years to measure the influence of various heavenly bodies such as the Sun, Moon, and planets on human life.  What we are familiar with as the most fundamental part of astrology today is the concept of the birth chart, which describes the picture of the heavens at the moment of a birth.  According to astrology, that picture is like a map of that human being's life.  
<Br><br>
That is a nice concept, but what does it actually mean?  There are so many variables, how can we know the effect of each one?  For example, what is the effect of Saturn when it is in one part of the sky at 2pm during the birth of a person in Fairfield, Iowa?  Is the influence different if the person is born at another time and place?  Is it different if Saturn is in a different part of the sky?  Can such things be measured?  If so, how?  These kinds of questions are extremely difficult to answer.  But for thousands of years, millions of people around the world have pondered these questions.  Many of those people have studied the heavens closely and devised measurement systems to divide the sky and track the movement of the heavenly bodies.  
<Br><br>
Interestingly, until the 16th century AD astronomy and astrology went hand in hand.  Ancient observers were so keen on measuring the heavens because they believed that there was a link between events in the universe and events on Earth.  The 16th -18th century separated astrology and astronomy as people began to focus on more scientific explanations.  Though it is difficult to prove that astrology is a science, we believe one major contributor to the ridicule of astrology was the inconsistencies caused by the separation of the Zodiacs.  But we will get to that a little later.  
<Br><br>
So how did such a complex system as astrology come into existence?  Was it trial and error, divine inspiration, or both?  Through the millennia there have been many names attached to important discoveries both astrological and astronomical that have come to define astrology as we know it today: Parashara, Ptolemy, Hipparchus, Copernicus, Keppler, Varahamihira, and so on.  But we're not going to get into that at this time.  With such an enormous body of knowledge that is astrology, it seems entirely possible that divine inspiration was involved.  But however astrology truly came to be, we have it now, and just like anything else that came from thousands of years ago there are many groups who all feel differently about how it "should" be done, and there is probably some truth to all of them.  
<Br><br>
Let's move forward and examine the astronomical aspect of astrology.  Astrology, being about how the heavens effect human life, takes a geocentric view of the universe.  This does not mean that astrologers today believe the Sun revolves around the Earth, but rather that they must use a system that shows the positions of the various heavenly bodies relative to the Earth as time goes by.  
<Br><br>
Here's how it works: To ancient observers the Earth appeared to be in the center of a giant revolving sphere of stars and heavens called the Celestial Sphere.  Though now we know that it is in fact the Earth that rotates causing the stars to appear to "rise" and "set", the Celestial Sphere is still an important development in astrology and astronomy.   
<Br><br>
Astronomers mapped stars in the Celestial Sphere, and used the fixed positions of those stars to further define the Earth's relationship to the Sun, Moon, and planets.  Since movement of the stars from the vantage point of Earth, aside from the Sun, is so minute it cannot be measured without high powered equipment, those stars were referred to as "fixed stars".  
<Br><br>
In a geocentric universe, the Sun appears to revolve around the Earth on a flat plane dividing the Celestial Sphere in half.  The Sun's apparent rotation around the Earth is the circumference of the Celestial Sphere.  
  <Br><br>
The Moon revolves around a plane at an angle of about 5° from the plane of the Sun's revolution.  Therefore, every once in a while, when the path of the Sun and the path of the Moon intersect, the Moon will come between the Earth and Sun, causing a Solar eclipse.  Because the use of Solar eclipses was so much a part of determining the Sun's apparent path around the Earth, that path was named the ecliptic.  
<Br><br>
After much observation using the fixed stars as reference points, it was determined that the planets never traveled further than 8° North or 8° South of the ecliptic.  This 16d wide belt circling the Earth is called the Zodiac, and at any time the heavenly bodies can be found somewhere within it.  
<Br><br>
The Zodiac was divided into 360°.  Each degree contains within it 60m and each minute contains 60s.  (Minutes and seconds are simply used as units of measurement and are not to be confused with standard time measurement.)  Since the Zodiac follows the ecliptic (the apparent path of the Sun around the Earth) it also follows the structure of a year.  With there being 12 months in a year astronomers/astrologers divided up the Zodiac into 12 equal 30° parts (360/12=30), naming each part after a constellation (Aries, Taurus, Gemini, etc.).  It is very important to note that the signs of the Zodiac are not the same as the actual constellations, they are simply named after constellations.  That is why this 13th constellation called Orphiucus does not pertain to the Zodiac.  
<Br><br>
There is another factor that further defined the relationship of the Earth to the Celestial Sphere that is called the Precession of the Equinoxes.  The Precession (backwards motion) of the Equinoxes is a term that is used to describe the wobbling of the Earth's axis.  Imagine a pole driven through the center of the Earth going from North to South, then imagine a giant hand (representing slight gravitational pull from the Sun, Moon and planets on the Earth) stirring that pole the same way one would stir a pot of stew.  That is how the Earth's North/South axis moves as it rotates and revolves around the Sun. 
<Br><br>
If you take a geocentric view for the sake of astrology, and the Earth's axis moves, then it follows that the Earth's relationship to the Celestial Sphere and the Zodiac will change over time.  To be more precise, the movement of the Earth's axis occurs at a rate of approximately 1° every 72 years, and a full 360° every 25,772 years.  The Precession of the Equinoxes is the reason for the difference between the Zodiacs today. 
<Br><br>
Claudius Ptolemy, an extremely influential figure in Western astrology, described his version of the construction of the Zodiac in the 2nd century.  He decided to use the Vernal equinox (about March 20) to define the starting point of the Zodiac (0° Aries) every year.  Though the discover of the Precession of the Equinoxes is recorded hundreds of years prior to Ptolemy, he chose to ignore it.  Ptolemy's decision tied the Zodiac to the seasons and divorced it from it's astronomically accurate.  Thus the Tropical Zodiac was born.  Though the two Zodiacs were aligned sometime in the 3rd century AD, the Sidereal Zodiac has been gradually moving backwards from the fixed position of the Tropical Zodiac (approx. 1° every 72 years), and will be continue to be misaligned for about 24,000 more years. 
<Br><br>
Let us come back to the present day and analyze the situation.  It has been about 1750 years since the two Zodiacs were aligned.  Using the rate of movement of the Earth's axis according to the Precession of the Equinoxes from earlier we find that, for people born in 2012, there is a difference of approximately 24.5° between the Sidereal and the Tropical Zodiacs.  Every year will has its own difference.  For example, 1983 has a difference of approximately 24°.  (Don't worry, we use much more precise calculations when determining your astrological chart!  This is only to demonstrate the principle.).    Since there are only 30° per Zodiac sign, we will find that about 82% (24.5/30) of all placements in 2012 will be found one sign earlier in the Sidereal Zodiac than the Tropical Zodiac.  To clarify, if you were born in 2012 and Tropical Sun is less that 24.5° into the sign of Libra at the time of your birth, then according to the Sidereal Zodiac your Sun will actually be in Virgo (the previous sign). 
<Br><br>
Herein lies the major difference between the Tropical Zodiac and the Sidereal Zodiac.  The Tropical Zodiac doesn't take into account the Precession of the Equinoxes, begins with 0d Aries on the Spring Equinox every year, and therefore ties the Zodiac to the seasons instead of the stars.  The Sidereal Zodiac, (Sidereal meaning "related to the stars") takes into account the Precession of the Equinoxes, begins with 0d Aries of the Zodiac according to its astronomical placement, and therefore ties the Zodiac to the stars and ignores the seasons.  
<Br><br>
We aren't here to say that there is "one right way".  We at Starma have studied astrology extensively using both the Sidereal and Tropical Zodiac for decades.  However, we believe that astrology was designed to measure the effects of the heavenly bodies on human life.  Since the Sidereal Zodiac takes the precession of the equinoxes into account and therefore places the Zodiac in its correct astronomical placement in relation to the Earth, we have decided to use the Sidereal Zodiac.  This is why you may find that the signs you once associated with in Western astrology have moved into the previous sign.  
<Br><br>
We sincerely hope that by reading this article you will understand why we have chosen this path.  We also wish to convey that we have the utmost respect for all people with a genuine interest in astrology whether they are partial to the Tropical or Sidereal Zodiac.  Please enjoy Starma with this in mind.  Thank you!

    <br><br>

    Sincerely,<br>
    The Starma Team--->
 </div> 
<?php
 //require_once "footer.php";
?> 