<?php
require_once "header.php"; 

 echo '<div id="two_zodiacs">
 	<br>
    <span style="font-size:2.2em; font-family:later_on; font-weight:bold; letter-spacing:2.2px;">A Tale of Two Zodiacs</span>
    <br>';

    echo '<div class="text_block" style="width:500px;">
<p>Thousands of years ago, as astronomers mapped the stars in the sky, they noticed that certain stars appeared to be in a fixed position and other "stars" appeared to travel.  These travelling “stars,” of course, were the planets. They named the path that the planets were traveling in the Zodiac, and divided this path into 12 parts.  Each of these parts included a constellation for which it was named, and the signs in a Birth Chart were determined by which constellation your planets, sun and moon were “traveling” through at your time of birth.  Even though we now know that the planets are not traveling around the earth but the sun, this doesn’t change the philosophy that your signs are determined by the relationship of the planets, Sun and Moon in the sky to the exact point you were born on earth.  This early Zodiac came to be called the Sidereal Zodiac, because sidereal means “in relation to the stars.”  To this day, Vedic Astrology uses the Sidereal Zodiac to calculate Birth Charts.</p>

<p>About 1800 years ago, when the Tropical Zodiac was created, the two Zodiacs generated almost exactly the same Birth Charts.  It’s possible that the introduction of the Tropical Zodiac went smoothly because there was little to no change when using this new Zodiac to calculate Birth Charts.  So 1800 years ago, if a neighbor who shared your birthday had her Birth Chart done by an astrologer using the Sidereal Zodiac and you had your Birth Chart done by an Astrologer using the Tropical Zodiac, there was likely no controversy when the two of you discussed yours Signs together.</p>

<p>What eventually created the disparity in Birth Charts is the fact that every year the earth tilts slightly on its axis, creating a change in the relationship of the earth to the stars overhead.  This means that in relation to the earth, the stars overhead at this moment are in a slightly different place than they will be at exactly this moment one year from today.  The Sidereal Zodiac takes this change into account, so while someone born between March 21st and April 19th roughly 1800 years ago would have been born under the constellation of Aries, nowadays someone would have to be born between April 14th and May 13th in order to be born under the constellation of Aries.</p>

<p>It was an astrologer named Claudius Ptolemy who created the Tropical Zodiac.  Ptolemy elected to divorce the Zodiac from the stars and tie it instead to the seasons and the solar year.  A solar year, also called a “tropical year,” is the time it takes for the sun to return to the same point in the sky, generally around one calendar year.  As such, Ptolemy’s Zodiac came to be known as the Tropical Zodiac.  Instead of considering the constellation the Sun was “passing through,” Ptolemy decided to divide the Sun’s path into 12 parts and call these the different signs of the Zodiac. In his model, the Zodiac no longer corresponded with the constellations in the sky, so even if a person today were born under the constellation of Aries, Ptolemy’s Zodiac might call that person a Taurus.  This is the Zodiac used in Western Astrology.</p>

<p>Using the Tropical Zodiac makes it so that everyone born on the same day, no matter the year or the constellation over head, will have the same Birth Chart.  Because, at Starma, we consider not just the relationship of the sun, the moon and the planets to the earth, but also the relationship of the stars, we choose to use the Sidereal Zodiac to calculate Birth Charts.  That being said, we believe astrology is an art, not a science.  Although for most of history astronomers were also astrologers, unlike astronomy, astrology cannot be proven in a scientific manner.  When you consider this, a belief that a Birth Chart should be determined by the Sun has as much merit as a belief that it should include the relationship of the stars.  Most of the features on Starma have been created using the Sidereal Zodiac, but for those of you interested in the Tropical Zodiac, we’ve included what we call the “Western View” on your profile.  Please enjoy the site, and email us with more questions.  We’ll be including a frequently asked questions section soon!</p>
</div>';

echo '</div>';

?>